### ISSUE TITLE
To start a exercises

### ISSUE THREAD

**Issue by js08** [linclark/algorithms-101#4]
Normally to start a node school exercises we run a npm command..is there any command for this one...for example functional js exercise has the following command below.

do we need to update installation guide.
https://github.com/timoxley/functional-javascript-workshop

Functional Javascript
npm install -g functional-javascript-workshop

**Comment by linclark** [comment]
For development, you'll want to fork the repo and then clone it.

Once you've done that, you can run `npm link` inside of the directory to make the `algorithms-101` command available.

**Comment by js08** [comment]
@linclark hey thanks for your reply...but can we make it into an npm package so that at-least this exercises others developers can try it out

**Comment by linclark** [comment]
I'm planning to finish a few more exercises before publishing it to npm.

**Comment by js08** [comment]
so until then can t we try this exercises

**Comment by linclark** [comment]
You can try it by cloning the repository.

A good way to get started with that is the Git-It workshopper:

```
npm install -g git-it
```

**Comment by js08** [comment]
I ran through those command but I get only this screens not the exercise screen...

![algorithms](https://cloud.githubusercontent.com/assets/1699943/4423140/51c74520-4592-11e4-816f-a7dc780c3f5f.PNG)

**Comment by linclark** [comment]
If you're having problems with the Git-It workshop, you'll want to post on https://github.com/nodeschool/discussions

**Comment by js08** [comment]
but for algorithms is it not still published...i was asking with respect to algorithms exercises...

**Comment by linclark** [comment]
In the other thread, my understanding was that you wanted to help with the development of this workshopper lesson. In order to do that, you need to know how to work with git. This is why I suggested the Git-It workshopper.

If your interest in this is as a user and not as a developer, then I'm sorry that I misunderstood. The lesson is currently not complete enough to be packaged up to npm.

**Comment by js08** [comment]
ok how many tasks your are left outin algorithms exercise...so that I can you help you out and we can do a publish...

**Comment by linclark** [comment]
If you look at the open issues in the issue queue, you'll see what needs to be added. Note that these should closely follow the format of the other exercises.

**Comment by js08** [comment]
hey did you see my post here..
https://github.com/linclark/algorithms-101/issues/1

**Comment by linclark** [comment]
yes, and I have responded there. That's about as much support as I can give on this. I have a fulltime job, so expecting immediate responses isn't going to work out.

**Comment by js08** [comment]
sorry about it..
