### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by grabbou** [linclark/algorithms-101#6]
Hey, 

Do you need some help with this workshop? From time to time, I always spend few hours to write some of the data structures and algorithms so this sounds like a good way to both help and practice at the same time!

**Comment by linclark** [comment]
Sure, there are two open issues which you could help with, if you like. The algorithms should look like the ones at http://algs4.cs.princeton.edu

**Comment by grabbou** [comment]
Ok, great. Thanks.
